/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PayoutPortalRouteImport } from './routes/payout-portal'
import { Route as ConnectedAccountRouteImport } from './routes/connected-account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTokenRouteImport } from './routes/api/token'
import { Route as ApiCreateConnectedAccountRouteImport } from './routes/api/create-connected-account'

const PayoutPortalRoute = PayoutPortalRouteImport.update({
  id: '/payout-portal',
  path: '/payout-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedAccountRoute = ConnectedAccountRouteImport.update({
  id: '/connected-account',
  path: '/connected-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateConnectedAccountRoute =
  ApiCreateConnectedAccountRouteImport.update({
    id: '/api/create-connected-account',
    path: '/api/create-connected-account',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/connected-account': typeof ConnectedAccountRoute
  '/payout-portal': typeof PayoutPortalRoute
  '/api/create-connected-account': typeof ApiCreateConnectedAccountRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/connected-account': typeof ConnectedAccountRoute
  '/payout-portal': typeof PayoutPortalRoute
  '/api/create-connected-account': typeof ApiCreateConnectedAccountRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/connected-account': typeof ConnectedAccountRoute
  '/payout-portal': typeof PayoutPortalRoute
  '/api/create-connected-account': typeof ApiCreateConnectedAccountRoute
  '/api/token': typeof ApiTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/connected-account'
    | '/payout-portal'
    | '/api/create-connected-account'
    | '/api/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/connected-account'
    | '/payout-portal'
    | '/api/create-connected-account'
    | '/api/token'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/connected-account'
    | '/payout-portal'
    | '/api/create-connected-account'
    | '/api/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConnectedAccountRoute: typeof ConnectedAccountRoute
  PayoutPortalRoute: typeof PayoutPortalRoute
  ApiCreateConnectedAccountRoute: typeof ApiCreateConnectedAccountRoute
  ApiTokenRoute: typeof ApiTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payout-portal': {
      id: '/payout-portal'
      path: '/payout-portal'
      fullPath: '/payout-portal'
      preLoaderRoute: typeof PayoutPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected-account': {
      id: '/connected-account'
      path: '/connected-account'
      fullPath: '/connected-account'
      preLoaderRoute: typeof ConnectedAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-connected-account': {
      id: '/api/create-connected-account'
      path: '/api/create-connected-account'
      fullPath: '/api/create-connected-account'
      preLoaderRoute: typeof ApiCreateConnectedAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConnectedAccountRoute: ConnectedAccountRoute,
  PayoutPortalRoute: PayoutPortalRoute,
  ApiCreateConnectedAccountRoute: ApiCreateConnectedAccountRoute,
  ApiTokenRoute: ApiTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
